### ISSUE TITLE
Inline script doesn't work

### ISSUE THREAD

**Issue by nt5689** [carlosgit2016/nodejs-runner#14]
I'm running an azure devops agent on windows 10.

When selecting inline script with content:
console.log("Hello");

The task execution ends with:

[section]Starting: NodeJSRunner 
==============================================================================
Task         : NodeJS Script Runner
Description  : Use this task in a build or release pipeline to run a JS script.
Version      : 0.4.2
Author       : Carlos Flor
Help         : [Learn more about this task](https://github.com/carlosgit2016/nodejs-runner) or [see the NodeJS Docs](https://nodejs.org/en/docs/)
==============================================================================
**[error]File not found: 'C:\agent\_work\_tasks\NodeJSRunner_6f432af8-1146-11ea-9a9f-362b9e155667\0.4.2\dist/sample.js'**
[section]Finishing: NodeJSRunner

**Comment by nt5689** [comment]
It seems the task is not correctly compiled. There is no sample.js file in the task folder on the agent.
There is no dist folder, so you forgot to compile the typescript with tsc before packaging. Would be nice if you could fix this.

**Comment by carlosgit2016** [comment]
Hi nt5689, I'm analysing to fix this. Thanks the feedback

**Comment by carlosgit2016** [comment]
Follow my test on [Azure DevOps](https://dev.azure.com/gabrielggff25/DummyProject/_build/results?buildId=563&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=6d13c9d1-e649-51b5-49a8-910d33269044) using a windows 10 agent.
